apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: authv1:latest
        imagePullPolicy: Never  # Ensure this line is added
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: AzureDBConnection_Users
          value: "Server=tcp:amitjoshipune.database.windows.net,1433;Initial Catalog=AzureTestDB;User ID=amitjoshipune;Password=Swara@12345;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="
        - name: AzureServiceBusWithTopics__connectionString
          value: "Endpoint=sb://amitservicebusnamespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=Pl4jzt2Deve4SLq8a+cPhS0c/au+rk0mw+ASbBL1tGo="
        - name: AzureServiceBusWithTopics__usersqueueName
          value: "userscreatedqueue"